### ISSUE TITLE
Can we install applications over IBM Installation Manager with this plugin?

### ISSUE THREAD

**Issue by imv7** [UrbanCode/IBM-Installation-Manager-UCD#1]
Hi,

We couldn't understand if does plugin allow us to use IBM IM to apply fixpack, for example, through UCD.

**Comment by nhmathis** [comment]
Hi,

This plug-in can be used to install or upgrade through the IBM Installation Manager. You'll want to use the `Install or Upgrade IBM Installation Manager` step.

**Comment by imv7** [comment]
Hi,

Can you share an example of flow?

**Comment by nhmathis** [comment]
Hi,

I was a slightly mistaken, the `Install/Upgrade` and `Uninstall` steps take advantage of the `installc`/`userinstc` and `uninstallc`/`userinstc` commands. (Exact command is based on admin/non-admin user.) These commands are used for installing/upgrading/uninstalling IBM Installation Manager itself. 

The `Execute Response File` step uses the `imcl` command line interface to install other products.

`Execute Response File` step configuration:
![image](https://user-images.githubusercontent.com/14111822/33720337-a85b45ac-db31-11e7-8940-a0f8fada4619.png)

Unfortunately, I do not have any sample flows to share. However, this plugin step follows the `imcl` documentation closely. Using the [imcl documenation](https://www.ibm.com/developerworks/community/wikis/home?lang=en#!/wiki/Installation+Manager+1.4.2/page/Installation+Manager+Command+Line), you should be able to construct the proper plugin configuration. If you are still having trouble, you can run the same `imcl` command through a Shell step as well.

Complete Step Documentation Listing: https://developer.ibm.com/urbancode/plugindoc/ibmucd/ibm-installation-manager/1-2/

**Comment by imv7** [comment]
I got it, this plugin allows us to install/uninstall IBM Installation Manager itself, and not use it's capability on installing a FixPack at WebSphere Application Server, for example. Am I Right? 

If so, Would you know how to install FixPack over UrbanCode?

**Comment by nhmathis** [comment]
You should be able to install any product's fixpack through the `Execute Response File` step. 

If you have trouble, simply run the `imcl` cli through a UCD Shell step. (`imcl` documentation is linked above.) If configuring this `imcl` call is new to you, I suggest trying to run it manually first.

**Comment by imv7** [comment]
AH ok, would you have an example on Execute Response File or imcl?

2017-12-07 16:35 GMT-02:00 Nick Mathison <notifications@github.com>:

**Comment by imv7** [comment]
ah ok, would you have an example on Execute Response File or imcl?

**Comment by nhmathis** [comment]
Unfortunately, I do not. Searching the IBM Knowledge Center for the `imcl` documentation is likely your best path to success.
